config/routes.rb
SouFudao::Application.routes.draw do

  resources :paypal_payments do
    collection do
      get '/featured_payment/:id' => "paypal_payments#featured_payment"
      get '/featured_payment_monthly' => "paypal_payments#featured_payment_monthly"
      get '/featured_payment_yearly' => "paypal_payments#featured_payment_yearly"
      get '/review/:id' => "paypal_payments#review"
      get '/cancel/:id' => "paypal_payments#cancel"      
      get '/cancel_recurring/:id' => "paypal_payments#cancel_recurring"            
      get '/make_recurring' => "paypal_payments#make_recurring"
      get '/notification/:payment_id' => "paypal_payments#notification"
    end
  end

  resources :user_details do
    collection do
      get 'update_password'
      get '/:id/profile_completion_step2' => 'user_details#profile_completion_step2'
      post '/:id/update_user_details' => 'user_details#update_user_details'
      put '/update_profile_visibility/:id' => 'user_details#update_profile_visibility'
      put '/email_updates_flag/:id' => 'user_details#email_updates_flag'

      patch '/save_user_avatar/:id' => "user_details#save_user_avatar"
      get '/remove_user_avatar/:id' => "user_details#remove_user_avatar"
      post '/:id/update_user_subjects' => 'user_details#update_user_subjects'
      post '/:id/update_user_info' => 'user_details#update_user_info'
      post '/:id/update_phone_info' => 'user_details#update_phone_info'

      get '/:id/profile_completion_step3' => 'user_details#profile_completion_step3'
      get '/save_listing_type/:id' => 'user_details#save_listing_type'
      get '/my_account/:id' => 'user_details#my_account'
      post '/:id/update_availability_info' => 'user_details#update_availability_info'
      post '/:id/update_location_details' => 'user_details#update_location_details'

      post '/save_user_avatar/:id' => "user_details#save_user_avatar"

      get 'add_time_select' => "user_details#add_time_select"
      get 'add_distance_select' => "user_details#add_distance_select"
      post '/invite_a_friend/:id' => "user_details#invite_a_friend"
      get 'add_more_degree' => "user_details#add_more_degree"
      get 'get_districts' => "user_details#get_districts"
    end
  end

  resources :tutors do
    collection do 
      get 'tutor/:id' => 'tutor#profile'
      get '/my_client/:id' => 'tutors#my_client'
      get '/settings/:id' => 'tutors#settings'
      get '/upgrade/:id' => 'tutors#upgrade'
      get '/my_messages/:id' => 'tutors#my_messages'      
      post '/:id/save_tutor_message' => 'tutors#save_tutor_message'
      get '/close_account/:id' => "tutors#close_account"
      post '/:id/confirm_close_account' => 'tutors#confirm_close_account'
      get '/student_close_account/:id' => "tutors#student_close_account"
      post '/:id/student_confirm_close_account' => 'tutors#student_confirm_close_account'
      get '/account_closed_message' => 'tutors#account_closed_message'

      post '/search' => 'tutors#search'
      get '/search' => 'tutors#search'
      post '/search_list_view' => 'tutors#search_list_view'
      get '/search_list_view' => 'tutors#search_list_view'

      get '/student/:id' => 'tutors#student'
      get '/student_setting/:id' => 'tutors#student_setting'
      get '/invite_students_friend/:id' => 'tutors#invite_students_friend' 
      post '/update_student_data/:id' => 'tutors#update_student_data'
      post '/tell_a_friend/:id' => 'tutors#tell_a_friend'
      post '/save_rate_reviews/tutor_id' => 'tutors#save_rate_reviews'
      get '/reload_capcha' => 'tutors#reload_capcha'
      post '/create_student_user' => "tutors#create_student_user"
      post '/student_sign_in' => "tutors#student_sign_in"
      get '/show_msg_conversation/:other_user_id' => "tutors#show_msg_conversation"
      post '/send_message_via_ajax' => "tutors#send_message_via_ajax"
      get '/student_messages/:id' => "tutors#student_messages" 
      get '/show_msg_conversation_for_student/:other_user_id' => "tutors#show_msg_conversation_for_student"
      get '/send_saved_message' => "tutors#send_saved_message"

    end
  end

  resources :subscriptions do
    collection do
      post '/request_to_yoopay' => "subscriptions#request_to_yoopay"
    end
  end

  get '/home' => 'home#index', as: 'home'
  get '/page_not_found' => 'home#page_not_found', as: 'page_not_found'
  get '/about' => 'home#about', as: 'about'
  get '/faq' => 'home#faq', as: 'faq'
  get '/contact' => 'home#contact', as: 'contact'
  get '/search_tutors' => "home#search_tutors"
  get '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  get '/notify_url' => 'subscriptions#notify_url'
  get '/return_url' => 'subscriptions#return_url'

  resources :home do
    collection do 
        post '/save_contact' => 'home#save_contact'
        get '/change_locale' => 'home#change_locale'
    end
  end

  devise_for :users
  

  root 'home#search_tutors'

end

app/models/paypal_payment.rb
class PaypalPayment < ActiveRecord::Base
	belongs_to :user
	attr_accessible :user_id, :token, :profile_id, :payer_id, :subscription_type, :profile_status, :start_date

	#set Profile status
	ACTIVE = "active"
	CANCEL = "cancelled"

	# set subscription period
	MONTH = "monthly"
	YEAR = "yearly"
end

app/controllers/paypal_payments_controller.rb
#!/bin/env: ruby
#encoding: utf-8

class PaypalPaymentsController < ApplicationController
require "paypal/recurring"
require 'digest/md5'
require 'uri'
require 'net/http'
require 'net/https'

def featured_payment_monthly
  featured_payment(PaypalPayment::MONTH)
end

def featured_payment_yearly
    featured_payment(PaypalPayment::YEAR)
end

def featured_payment(subscription_type)
  @user = User.find_by_id(params[:id])
  ppr = PayPal::Recurring.new({
    :return_url   => "http://#{request.host_with_port}" + "/paypal_payments/review/#{@user.id}?type=#{subscription_type}",
    :cancel_url   => "http://#{request.host_with_port}" + "/paypal_payments/cancel/#{@user.id}",
    :description  => get_recurring_payment_description(subscription_type),
    :amount       => get_recurring_payment_amount(subscription_type),
    :currency     => get_recurring_payment_currency
  })
  response = ppr.checkout
  redirect_to response.checkout_url if response.valid? 
end  

def review
  @user = User.find_by_id(params[:id])
  unless (params["token"].blank? && params[:PayerID].blank?)
    @paypal_payment = PaypalPayment.new(:user_id => @user.id,token: params["token"], payer_id: params["PayerID"], :subscription_type => params[:type])
    @paypal_payment.save
    make_recurring(@paypal_payment)
  else
    redirect_to :action => "cancel", :id=> @user.id
  end  
end

  def make_recurring(paypal_payment)
    @paypal_payment = paypal_payment
    ppr_recurring = PayPal::Recurring.new({
        :amount      => get_recurring_payment_amount(@paypal_payment.subscription_type),
        :currency    => get_recurring_payment_currency,
        :description => get_recurring_payment_description(@paypal_payment.subscription_type),
        :frequency   => 1,
        :token       => "#{@paypal_payment.token}",
        :period      => (@paypal_payment.subscription_type == PaypalPayment::MONTH) ? :monthly : :yearly,
        :payer_id    => "#{@paypal_payment.payer_id}",
        :start_at    => Time.now,
      })
      recurring = ppr_recurring.create_recurring_profile
      puts recurring.to_json
      if(recurring.ack.downcase == "success")
        pay_response = make_payment(@paypal_payment)
        if (pay_response.approved? && pay_response.completed?)
          @paypal_payment.update(:profile_id => recurring.profile_id, :profile_status=> PaypalPayment::ACTIVE, :start_date=> Time.now.to_date) if recurring.profile_id
          @paypal_payment.user.user_detail.update(:listing_type => false,:is_plan_selected? => true) if recurring.profile_id
          flash[:notice] = "Thanks for the Payment!! Your recurring profile has been created successfully."
        else
          flash[:notice] = "Sorry!! Payment cannot be completed. Please try again."
        end
      else
        flash[:notice] = "Your recurring profile has not been created."        
      end
      redirect_to :controller => "user_details", :action => "my_account", :id => @paypal_payment.user.user_detail.id
  end

  def make_payment(payment_detail)
    @paypal_payment = payment_detail
    ppr = PayPal::Recurring.new({
      :token       => "#{@paypal_payment.token}",
      :payer_id    => "#{@paypal_payment.payer_id}",
      :amount      => get_recurring_payment_amount(@paypal_payment.subscription_type),
      :description => get_recurring_payment_description(@paypal_payment.subscription_type)
    })
    response = ppr.request_payment
  end

  def cancel
    @user = User.find_by_id(params[:id])
    redirect_to :controller => "tutors", :action=>"upgrade", :id=>@user.user_detail.id
  end

  def cancel_recurring
    @paypal_payment = User.find(params[:id]).paypal_payments.last
    ppr = PayPal::Recurring.new(:profile_id => @paypal_payment.profile_id)
    res = ppr.cancel
    if(res.ack.downcase == "success")  
      @paypal_payment.update(:profile_status=> PaypalPayment::CANCEL)
      flash[:notice] = "Your recurring profile has been cancelled successfully."
    else
      flash[:error] = "Sorry!! Your recurring profile cannot be cancelled. Please try again."
    end
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paypal_payment
      @paypal_payment = PaypalPayment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paypal_payment_params
      params.require(:paypal_payment).permit(:user_id, :payer_id, :token, :profile_id, :subscription_type, :profile_status, :start_date)
    end
end

#response
#<PayPal::Recurring::Response::Payment:0xd51b8d4 @response=#<Net::HTTPOK 200 OK readbody=true>, @params={:TOKEN=>"EC-7G373229L34997232", :SUCCESSPAGEREDIRECTREQUESTED=>"false", :TIMESTAMP=>"2013-12-20T09:56:26Z", :CORRELATIONID=>"a97ec7e2244b3", :ACK=>"Success", :VERSION=>"72.0", :BUILD=>"8951431", :INSURANCEOPTIONSELECTED=>"false", :SHIPPINGOPTIONISDEFAULT=>"false", :PAYMENTINFO_0_TRANSACTIONID=>"3D411814UE533882N", :PAYMENTINFO_0_TRANSACTIONTYPE=>"expresscheckout", :PAYMENTINFO_0_PAYMENTTYPE=>"instant", :PAYMENTINFO_0_ORDERTIME=>"2013-12-20T09:56:26Z", :PAYMENTINFO_0_AMT=>"9.00", :PAYMENTINFO_0_FEEAMT=>"0.56", :PAYMENTINFO_0_TAXAMT=>"0.00", :PAYMENTINFO_0_CURRENCYCODE=>"USD", :PAYMENTINFO_0_PAYMENTSTATUS=>"Completed", :PAYMENTINFO_0_PENDINGREASON=>"None", :PAYMENTINFO_0_REASONCODE=>"None", :PAYMENTINFO_0_PROTECTIONELIGIBILITY=>"Ineligible", :PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE=>"None", :PAYMENTINFO_0_SECUREMERCHANTACCOUNTID=>"YFE2XJ7BX59S2", :PAYMENTINFO_0_ERRORCODE=>"0", :PAYMENTINFO_0_ACK=>"Success"}>

#recurring
#{"response":{"server":["Apache"],"content-length":["316"],"content-type":["text/plain; charset=utf-8"],"dc":["origin2-api-3t.sandbox.paypal.com"],"date":["Fri, 20 Dec 2013 09:56:39 GMT"],"connection":["close"],"set-cookie":["DC=origin2-api-3t.sandbox.paypal.com; secure"]}}

#ppr_recurring
#<PayPal::Recurring::Base:0xc952868 @description="TutorApp - Yearly Subscription", @amount="89.00", @currency="USD", @frequency=1, @token="EC-19D317902Y3916022", @period=:yearly, @payer_id="2HNHUW7USJ6AU", @start_at=2013-12-20 00:05:01 +0530>

app/helpers/paypal_payments_helper.rb
module PaypalPaymentsHelper
end

app/views/paypal_payments/_form.html.erb
<%= form_for(@paypal_payment) do |f| %>
  <% if @paypal_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paypal_payment.errors.count, "error") %> prohibited this paypal_payment from being saved:</h2>

      <ul>
      <% @paypal_payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :payer_id %><br>
    <%= f.text_field :payer_id %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paypal_payments/edit.html.erb
<h1>Editing paypal_payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @paypal_payment %> |
<%= link_to 'Back', paypal_payments_path %>

app/views/paypal_payments/index.html.erb
<h1>Listing paypal_payments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Payer</th>
      <th>Token</th>
      <th>Profile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @paypal_payments.each do |paypal_payment| %>
      <tr>
        <td><%= paypal_payment.user_id %></td>
        <td><%= paypal_payment.payer_id %></td>
        <td><%= paypal_payment.token %></td>
        <td><%= paypal_payment.profile_id %></td>
        <td><%= link_to 'Show', paypal_payment %></td>
        <td><%= link_to 'Edit', edit_paypal_payment_path(paypal_payment) %></td>
        <td><%= link_to 'Destroy', paypal_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paypal payment', new_paypal_payment_path %>

app/views/paypal_payments/new.html.erb
<h1>New paypal_payment</h1>

<%= render 'form' %>

<%= link_to 'Back', paypal_payments_path %>

app/views/paypal_payments/request_to_yoopay.html.erb
<html>
	<head>
		<script type="text/javascript" src="jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="show5.js"></script>
	</head>
	<body>
		<form>
		<input type="radio" name="pay_radio" value="99"/>For Teacher: 99</br>
		<input type="radio" name="pay_radio" value="199"/>For Student: 199</br>
		UserName:<input type="input" id="user" /></br>
		<input type="button" name="pay" value="pay" onclick="to_pay()" />
		</form>
	</body>
</html>

app/views/paypal_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @paypal_payment.user_id %>
</p>

<p>
  <strong>Payer:</strong>
  <%= @paypal_payment.payer_id %>
</p>

<p>
  <strong>Token:</strong>
  <%= @paypal_payment.token %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @paypal_payment.profile_id %>
</p>

<%= link_to 'Edit', edit_paypal_payment_path(@paypal_payment) %> |
<%= link_to 'Back', paypal_payments_path %>