config/routes.rb
SouFudao::Application.routes.draw do

  resources :paypal_payments do
    collection do
      get '/featured_payment/:id' => "paypal_payments#featured_payment"
      get '/featured_payment_monthly' => "paypal_payments#featured_payment_monthly"
      get '/featured_payment_yearly' => "paypal_payments#featured_payment_yearly"
      get '/review/:id' => "paypal_payments#review"
      get '/cancel/:id' => "paypal_payments#cancel"      
      get '/cancel_recurring/:id' => "paypal_payments#cancel_recurring"            
      get '/make_recurring' => "paypal_payments#make_recurring"
      get '/notification/:payment_id' => "paypal_payments#notification"
    end
  end

  resources :user_details do
    collection do
      get 'update_password'
      get '/:id/profile_completion_step2' => 'user_details#profile_completion_step2'
      post '/:id/update_user_details' => 'user_details#update_user_details'
      put '/update_profile_visibility/:id' => 'user_details#update_profile_visibility'
      put '/email_updates_flag/:id' => 'user_details#email_updates_flag'

      patch '/save_user_avatar/:id' => "user_details#save_user_avatar"
      get '/remove_user_avatar/:id' => "user_details#remove_user_avatar"
      post '/:id/update_user_subjects' => 'user_details#update_user_subjects'
      post '/:id/update_user_info' => 'user_details#update_user_info'
      post '/:id/update_phone_info' => 'user_details#update_phone_info'

      get '/:id/profile_completion_step3' => 'user_details#profile_completion_step3'
      get '/save_listing_type/:id' => 'user_details#save_listing_type'
      get '/my_account/:id' => 'user_details#my_account'
      post '/:id/update_availability_info' => 'user_details#update_availability_info'
      post '/:id/update_location_details' => 'user_details#update_location_details'

      post '/save_user_avatar/:id' => "user_details#save_user_avatar"

      get 'add_time_select' => "user_details#add_time_select"
      get 'add_distance_select' => "user_details#add_distance_select"
      post '/invite_a_friend/:id' => "user_details#invite_a_friend"
      get 'add_more_degree' => "user_details#add_more_degree"
      get 'get_districts' => "user_details#get_districts"
    end
  end

  resources :tutors do
    collection do 
      get 'tutor/:id' => 'tutor#profile'
      get '/my_client/:id' => 'tutors#my_client'
      get '/settings/:id' => 'tutors#settings'
      get '/upgrade/:id' => 'tutors#upgrade'
      get '/my_messages/:id' => 'tutors#my_messages'      
      post '/:id/save_tutor_message' => 'tutors#save_tutor_message'
      get '/close_account/:id' => "tutors#close_account"
      post '/:id/confirm_close_account' => 'tutors#confirm_close_account'
      get '/student_close_account/:id' => "tutors#student_close_account"
      post '/:id/student_confirm_close_account' => 'tutors#student_confirm_close_account'
      get '/account_closed_message' => 'tutors#account_closed_message'

      post '/search' => 'tutors#search'
      get '/search' => 'tutors#search'
      post '/search_list_view' => 'tutors#search_list_view'
      get '/search_list_view' => 'tutors#search_list_view'

      get '/student/:id' => 'tutors#student'
      get '/student_setting/:id' => 'tutors#student_setting'
      get '/invite_students_friend/:id' => 'tutors#invite_students_friend' 
      post '/update_student_data/:id' => 'tutors#update_student_data'
      post '/tell_a_friend/:id' => 'tutors#tell_a_friend'
      post '/save_rate_reviews/tutor_id' => 'tutors#save_rate_reviews'
      get '/reload_capcha' => 'tutors#reload_capcha'
      post '/create_student_user' => "tutors#create_student_user"
      post '/student_sign_in' => "tutors#student_sign_in"
      get '/show_msg_conversation/:other_user_id' => "tutors#show_msg_conversation"
      post '/send_message_via_ajax' => "tutors#send_message_via_ajax"
      get '/student_messages/:id' => "tutors#student_messages" 
      get '/show_msg_conversation_for_student/:other_user_id' => "tutors#show_msg_conversation_for_student"
      get '/send_saved_message' => "tutors#send_saved_message"

    end
  end

  resources :subscriptions do
    collection do
      post '/request_to_yoopay' => "subscriptions#request_to_yoopay"
    end
  end

  get '/home' => 'home#index', as: 'home'
  get '/page_not_found' => 'home#page_not_found', as: 'page_not_found'
  get '/about' => 'home#about', as: 'about'
  get '/faq' => 'home#faq', as: 'faq'
  get '/contact' => 'home#contact', as: 'contact'
  get '/search_tutors' => "home#search_tutors"
  get '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  get '/notify_url' => 'subscriptions#notify_url'
  get '/return_url' => 'subscriptions#return_url'

  resources :home do
    collection do 
        post '/save_contact' => 'home#save_contact'
        get '/change_locale' => 'home#change_locale'
    end
  end

  devise_for :users
  

  root 'home#search_tutors'

end

app/controllers/tutors_controller.rb
#!/bin/env: ruby
#encoding: utf-8

class TutorsController < ApplicationController
  
	
	#before_filter :check_login_profile_done, :only => [:my_client]
	protect_from_forgery :except => [:search]
	before_action :authenticate_user!, only: [:my_client,:upgrade, :settings, :my_messages, :student_messages]
	before_action :check_if_tutor_profile_completed, only: [:show]
	

	def show
		@tutor = User.find(params[:id])
		@hash = Gmaps4rails.build_markers([@tutor]) do |t, marker|
		  marker.lat t.user_detail.latitude
		  marker.lng t.user_detail.longitude
		  # marker.infowindow user_detail.experience
	      marker.picture({
	      "url" => "/assets/blue_pointer.png",
	      "width" =>  32,
	      "height" => 32})
		end
	end

	def my_client
		@user_detail = UserDetail.find(params[:id])	
		@tutor_messages = UserMessage.all.where(:user_id => @user_detail.user_id).order("created_at DESC").page(params[:page]).per(5)
	end

	def save_tutor_message
		if simple_captcha_valid?
			session[:msg] = params[:user_messages]
			check_user_exists = User.exists?(:email => params[:user_messages][:sender_email])
			@exist_user	= User.where(:email => params[:user_messages][:sender_email])[0] if check_user_exists		
			if (user_signed_in?)
				if (current_user.is_tutor?) #if current_user = tutor
					flash[:notice] = (session[:locale] != 'cn') ? "Sorry, tutors can't contact other tutors through this website." : "对不起，老师不能通过此网页互相联系。"
				else (!current_user.is_tutor?) #if current_user = student
					is_student_created = [true, @exist_user.id]
					send_msg(params[:user_messages], is_student_created)
				end
			else
				if (check_user_exists)
					if (@exist_user.is_tutor?) #if msg_sender = tutor
						flash[:notice] = (session[:locale] != 'cn') ? "Sorry, tutors can't contact other tutors through this website." : "对不起，老师不能通过此网页互相联系。"
					else
						flash[:show_sign_in] = true
					end
				else
					flash[:show_sign_up] = true
				end
			end	
		else
			flash[:captcha_err] = (session[:locale] != 'cn') ? "Please type in the correct verification letters." : "请输入正确的验证码。"
		end
	end

	def send_msg(usr_msgs,created_student_flag)
		@user_message = UserMessage.new(usr_msgs)
		if (created_student_flag[0] && @user_message.save)
			@user_message.update(:student_id => created_student_flag[1])
			UserMailer.send_tutor_a_message(@user_message, request.host_with_port).deliver
			flash[:notice] = (session[:locale] != "cn") ? "Thank you, your message has been sent! Feel free to contact other tutors while you wait. Most tutors respond within 48 hours."
      : "谢谢，您的信息已发出！您可以继续和其他老师联系。大部分老师会在48小时内会联系您"
		else
			flash[:error] = (session[:locale] != "cn") ? "Please try again." : "请再试一次。"
		end
	end

	def create_student_user
		@student_user = User.new(:first_name=> params[:users][:first_name], :email => params[:users][:email], :password => params[:users][:password], :is_tutor? => false)
		@student_user.skip_confirmation!
			if @student_user.save	
				@tutor_user = User.find(session[:msg][:user_id])
				UserMailer.account_mail_to_student(@student_user, params[:users][:password], @tutor_user, request.host_with_port).deliver			
				send_msg(session[:msg], [true, @student_user.id])
			else
				send_msg(session[:msg], [false, @student_user.id])
			end
	end

	def send_saved_message
		if session[:msg]
			@user_message = UserMessage.new(session[:msg])
			@user_message.update(:student_id => current_user.id)
			UserMailer.send_tutor_a_message(@user_message, request.host_with_port).deliver
			flash[:notice] = (session[:locale] != "cn") ? "Thank you, your message has been sent! Feel free to contact other tutors while you wait. Most tutors respond within 48 hours."
      : "谢谢，您的信息已发出！您可以继续联系其他老师，大部分老师会在48小时内回复您。"
	    end
	    render :json => {:status => 'ok'}
	end

	def settings
		@user_detail = UserDetail.find(params[:id])	
	end
	
	def close_account
		@user_detail = UserDetail.find(params[:id])
	end

	def upgrade
		@user_detail = UserDetail.find(params[:id])
	end

	def confirm_close_account
		@user = UserDetail.find(params[:id]).user
		if @user.destroy
			 sign_out @user
			 redirect_to :action => "account_closed_message"
		else
      flash[:error] = (session[:locale] != "cn") ? "Please try again." : "请再试一次。"
			redirect_to :back
		end	
	end

	def student_close_account
		@user = User.find(params[:id])
	end

	def student_confirm_close_account
		@user = User.find(params[:id])
		if @user.destroy
			 sign_out @user
			 redirect_to :action => "account_closed_message"
		else
      flash[:error] = (session[:locale] != "cn") ? "Please try again." : "请再试一次。"
			redirect_to :back
		end	
	end	

	def account_closed_message
	end
	#This method is used to check if user is logged in and profile completed then only access /tutors/:id
	def check_login_profile_done
		unless (user_signed_in? && current_user.user_detail.is_user_profile_done?)
			redirect_to root_path
		end	
	end

	def search
	      city_states = YAML.load_file('config/city_states.yml')
	      @cities = city_states['china'].keys
	      @districts = params[:city] ? city_states['china']["#{params[:city]}"] : city_states['china']['Shanghai']
		if params[:subject].present?
			if params[:subject] == 'Any subject'
				@user_details = UserDetail.all.order('listing_type ASC')
			else
				@user_details = UserDetail.where('LOWER(subject) like (?)', "%#{params[:subject].downcase}%").order('listing_type ASC')
			end		
		else
			@user_details = UserDetail.all.order('listing_type ASC')
		end	
		if !@user_details.nil? && params[:city].present?
				@user_details = @user_details.near(params[:city], 40).order('listing_type ASC')  
		end
		@user_details = @user_details.select { |r| r.will_profile_visible? }
		#@user_details = @user_details.order('availabilities.price') if params[:sort] == 'price'
		if params[:sort] == 'price'
			@user_details = @user_details.sort{|a,b| a.user.availability.price <=> b.user.availability.price } 
			@user_details = @user_details = @user_details.sort_by { |a| a.listing_type ? 1 : 0 }
		end	
		if params[:sort] == 'rating'
			@user_details = @user_details.sort{|a,b| b.average_rating <=> a.average_rating } 
			@user_details = @user_details.sort_by { |a| a.listing_type ? 1 : 0}
		end		
		unless @user_details.kind_of?(Array)		
		  @user_details = @user_details.page(params[:page]).per(10)
		else
		  @user_details = Kaminari.paginate_array(@user_details).page(params[:page]).per(10)
		end
		
		pointer = ('A'..'J').to_a 
		i = 0
		@hash = Gmaps4rails.build_markers(@user_details) do |user_detail, marker|
		  marker.lat user_detail.latitude
		  marker.lng user_detail.longitude
		  # marker.infowindow user_detail.experience
	      marker.picture({
	      "url" => "/assets/blue_pointer.png",
	      "width" =>  25,
	      "height" => 40})
	      marker.infowindow render_to_string(:partial => "/tutors/map_pop", :locals => { :user_detail => user_detail})
	      i+=1
		end
		if request.xhr?
		    respond_to do |format|
		      format.js
		      format.html
		    end
		end
	end

	def search_list_view
	      city_states = YAML.load_file('config/city_states.yml')
	      @cities = city_states['china'].keys
	      @districts = params[:city] ? city_states['china']["#{params[:city]}"] : city_states['china']['Shanghai']

		if params[:subject].present?
			if params[:subject] == 'Any subject'
				@user_details = UserDetail.all.order('listing_type ASC')
			else
				@user_details = UserDetail.where('LOWER(subject) like (?)', "%#{params[:subject].downcase}%").order('listing_type ASC')
			end		
		else
			@user_details = UserDetail.all.order('listing_type ASC')
		end	
		if !@user_details.nil? && params[:city].present?
				@user_details = @user_details.near(params[:city], 40) 
		end
		#@user_details = @user_details.order('availabilities.price').reverse_order if params[:sort] == 'price'
		@user_details = @user_details.select { |r| r.will_profile_visible? }
		if params[:sort] == 'price'
			@user_details = @user_details.sort{|a,b| a.user.availability.price <=> b.user.availability.price } 
			@user_details = @user_details = @user_details.sort_by { |a| a.listing_type ? 1 : 0 }
		end	
		if params[:sort] == 'rating'
			@user_details = @user_details.sort{|a,b| b.average_rating <=> a.average_rating } 
			@user_details = @user_details = @user_details.sort_by { |a| a.listing_type ? 1 : 0 }
		end
		unless @user_details.kind_of?(Array)
		  @user_details = @user_details.page(params[:page]).per(10)
		else
		  @user_details = Kaminari.paginate_array(@user_details).page(params[:page]).per(10)
		end
		
	end

	def student
		@user = User.find(params[:id])
		@msgs = UserMessage.select("max(id) as id").where("student_id=#{@user.id}").group("user_id").order("id DESC")		
	end

	def student_setting
		@user = User.find(params[:id])		
	end

	def invite_students_friend
		@user = User.find(params[:id])				
	end

	def update_student_data
		@user = User.find(params[:id])
		if @user.update(:email => params[:tutors][:email], :first_name => params[:tutors][:first_name])
			flash[:notice] = (session[:locale] != "cn") ? "Updated successfully" : "更新成功"
		else
      flash[:error] = (session[:locale] != "cn") ? "Please try again." : "请再试一次。"
		end
		redirect_to :back
	end

	def tell_a_friend
		@user = User.find(params[:id])
		if UserMailer.invite_to_student_friend(params[:email], params[:subject], params[:message], @user).deliver
			flash[:notice] = (session[:locale] != "cn") ? "Your message has been sent. Thank you!\n
      To send another simply type another email address." : "您的信息已发出了。"
		else
			flash[:error] = (session[:locale] != "cn") ? "Sorry, the message could not be sent. Please try again." : "对不起，邮件未发出。请再试一次。"
		end
		redirect_to :back
	end

	def save_rate_reviews
		@user_review = TutorReview.new(params[:tutor_review])
		if @user_review.save
			UserMailer.review_mail_to_tutor(@user_review, request.host_with_port).deliver			
			flash[:notice] = (session[:locale] != "cn") ? "Rating posted successfully" : "评价成功"
		else

app/helpers/tutor_helper.rb
module TutorHelper
end

app/views/tutors/_after_login_student_header.html.erb
<div id="top">
  <div class="wrapper" data-no-turbolink>
    <h2><%= t('my_acc') %></h2>
    <ul id="tabs" class="account">
     <li class="">
        <a href="/tutors/invite_students_friend/<%= @user.id %>" class="menu" id="tab_4"><%= t('student_account.tell_a_frend') %></a>
      </li>    
      <li class="">
        <a href="/tutors/student_setting/<%= @user.id %>" class="menu" id="tab_3"><%= t('student_account.settings') %></a>
      </li>
      <li class="">
        <a href="/tutors/student/<%= @user.id %>" class="menu" id="tab_2"><%= t('student_account.ratings') %></a>      
      </li>  
      <li class="">
        <a href="/tutors/student_messages/<%= @user.id %>" class="menu" id="tab_1"><%= t('student_account.my_messages') %></a>
      </li>           
    </ul>
  </div>
</div>

<script type="text/javascript">
$('a.menu').click(function(){
    $('a.menu').parent().removeClass("active");
    $(this).parent().addClass("active");
});
</script>

app/views/tutors/_show_msg_conversation_for_student.html.erb
<% other_user = UserMessage.where("student_id = #{params[:other_user_id]}").first %>
  <div class="row">
    <%= form_for(:user_messages, :url => {:controller=> "tutors",:action=>"send_message_via_ajax"}, :html => {:id=>"tutor_ajax_contact_form", :method => :post, :remote => true}) do |f| %>
    <div style="width: 91%; margin-left: 20px;">
        <%= f.hidden_field :user_id, :value => params[:other_user_id] %>
        <%= f.hidden_field :student_id, :value => @user.id %>
        <%= f.hidden_field :sender_phone, :value => (other_user.blank? ? "" : other_user.sender_phone) %>
        <%= f.hidden_field :sender_name, :value => (other_user.blank? ? "" : other_user.sender_name) %>
        <%= f.hidden_field :sender_email, :value => (other_user.blank? ? "" : other_user.sender_email) %>
        <%= f.label "#{t('my_messages.enter_msg')}:"%>
        <%= f.text_area :message, :style =>"width:100%;" %>
        <span id="user_messages_message_error" style="color:red;"></span>
    </div>
    <div class="span4">
      <div class="profilesubmit">
        <input class="btn-orange mtop6" type="submit" value="<%= t('my_messages.post_msg') %>"  name="commit">
      </div>
    </div>
    <% end%>
  </div>          


<br/>
<div id="scroll_to_div" class="msg_chat_box">
  <div id="success_box"></div>
  <div class="table table-striped chat_list" id="tbldata">
    <ul class="dark_bg">
      <li class="invoice_header"><%= t('my_messages.sender') %></li>
      <li class="invoice_header wdt70"><%= t('my_messages.message') %></li>
      <li class="invoice_header wdt18"><%= t('my_messages.date') %></li>
     </ul>

     <div class="new_scroll_col">
<% unless @all_msgs.blank? %>
           <% counter = 0 %>
    <% @all_msgs.each do |msg|%>
         <% wht_bg = counter % 2 == 0 ? "pro_white_bg" : "" %>
         <ul class="<%= wht_bg %>">
          <li>
            <%= get_msg_sender(msg) %>
          </li>
              <li class="wdt70">
            <%= msg.message %>
         </li>
              <li class="wdt18">
            <%= msg.created_at.strftime("%Y-%m-%d %H:%M:%S %Z") %>
          </li>
            </ul>
                <% counter += 1 %>
    <% end %>
<% else %>
       </div>

          <div class="invoice_footer"> <%= t('student_account.no_msg')%>  </div>

<% end %>    
     </div>

</div>

<script type="text/javascript">
  

    $('#tutor_ajax_contact_form').validate(
    {

      rules: {
        "user_messages[message]": {
          required: true,
        }
      },

      messages: {
        "user_messages[message]":{
          required: "Please enter a Message."
        }
      },

      showErrors: function (errorMap, errorList) {

        $.each(this.successList, function (index, value) {
          //console.log(value.id)
          $("#"+value.id+"_error").html(" ");
          $("#"+value.id).css("border","1px solid #CCCCCC");
        });
        $.each(errorList, function (index, value) {
          //console.log(value.element.id);
          //console.log(value.message);
          $("#"+value.element.id+"_error").html(value.message);
          $("#"+value.element.id).css("border","1px solid red");
        });

      }      
    });

$(document).ready(function(){
  $('#user_messages_message').autosize();
});

</script>

app/views/tutors/_sign_in_form.html.erb
<div id="student_sign_in" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:400px;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h2 id="myModalLabel"><%= t 'sign_in.please_sign_in'%></h2>
  </div>
    <div class="modal-body">
        <div class="body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name),:html=>{:id=>"sign_in_form"}, :remote => :true, :format => :json) do |f| %>
          <div><label><%= t 'sign_in.email' %></label>
            <%= f.email_field :email, :readonly => true, :class => "text-field" %></div>

          <div><label style = "float:left;"><%= t 'sign_in.password'%></label>
           <a style="float:right;" href="/users/password/new"><%= t 'sign_in.forget_pass' %></a>
            <%= f.password_field :password, :class => "text-field" %></div>
            <span id="sign_in_password_error" style="color:red;"></span>
          <div>
          <input class="btn-orange" type="submit" value="<%= t 'sign_in.login_btn_txt' %>" style="float:left;width:30%;" name="commit">
        </div>
          <% if devise_mapping.rememberable? -%>
            <div style="float:right;">
              <label class="checkbox">
                <%= f.check_box :remember_me %><%= t 'sign_in.remember' %>
              </label>
            </div>
          <% end -%>          
        <% end %>
        <br/>
       
  </div>
    </div> 
</div>

app/views/tutors/_sign_up_form.html.erb
<div id="myModalSignUp" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= t('student_sign_up.heading')%></h3>
  </div>
  <%= form_for(:users, :url => {:controller=> "tutors",:action=>"create_student_user"}, :html => {:id=>"student_login_form", :method => :post, :remote => true}) do |f| %>
    <div class="modal-body">
      <div>
        <%= f.label "#{t('student_sign_up.stud_name')}" %>
        <%= f.text_field :first_name, :readonly => true, :class => "text-field" %>
      </div>
      <div>
        <%= f.label "#{t('student_sign_up.stud_email')}" %>
        <%= f.email_field :email,:readonly => true, :class => "text-field" %>
      </div>
      
      <div>
        <%= f.label "#{t('student_sign_up.stud_confirm_email')}" %>
        <%= f.text_field :email_confiramation, :class => "text-field"%>
        <span id="users_email_confiramation_error" style="color:red;"></span>
      </div>
      
      <div>
        <%= f.label "#{t('student_sign_up.password')}"  ,:style => "float:left;"%>
        <%= f.password_field :password, :class => "text-field" %>
        <span id="users_password_error" style="color:red;"></span>
      </div>
      <div>
                  <input type="checkbox" style="margin-left:25px;float:left;" id="agree" name="agree" />
                  <label for="agree">&nbsp; <%= t 'sign_up.i_agree' %><% unless session[:locale] == 'cn'%>&nbsp;<% end %><a href="javascript:void(0);" onclick="$('#terms_model').modal();"><%= t 'sign_up.terms_and_conditions' %></a></label>
                  <span id="agree_error" style="color:red;"></span>        
      </div>
    </div>
    <div class="modal-footer"> 
      <input class="btn btn-medium btn-success" type="submit" value="<%= t('student_sign_up.create_btn')%>" style="float:left;width:125px;" name="commit">
    </div>
  <% end %>
</div>


<div class="modal hide" id="terms_model">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel"><b>Sou Fudao Terms of Use</b></h3>
      </div>
      <div class="modal-body">
      <%= render :partial => "terms_of_use_for_student"%>  
      </div>
    </div>
  </div>
</div>

app/views/tutors/close_account.html.erb
<div class="wrapper">
  <div class="nice-box close-account" id="login">
    <div class="header">
      <h2><%= t('settings.close_heading') %></h2>
    </div>
    <div class="body">
      <%= t('settings.close_txt') %>
      <br><br>
      
      <form method="post" action="/tutors/<%= @user_detail.id%>/confirm_close_account">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <input type="hidden" value="yes" name="confirm" id="confirm">
        <input type="submit" value="<%= t('settings.close_confirm') %>" name="commit">
      <%= t('settings.or') %>
         <a class="cancel" href="/tutors/settings/<%= @user_detail.id%>"><%= t('settings.close_cancel') %></a>
      </form>
    </div>
  </div>
</div>

app/views/tutors/confirm_close_account.html.erb
<div class="wrapper">
  <div class="nice-box close-account" id="login">
    <div class="header">
      <h2><%= t('settings.confirm_heading') %></h2>
    </div>
    <div class="body">
      <%= t('settings.txt_1') %>
      <br><br>
      <%= t('settings.txt_2') %> <a href="/contact"><%= t('settings.txt_3') %></a>.  <%= t('settings.txt_4') %>
    </div>
  </div>
</div>

app/views/tutors/create_student_user.js.erb
<% if flash[:notice] %>
$('#myModalSignUp').modal('hide');
$(window).scrollTop($('#contact_form_box').offset().top);
$('#inner_contact_box').replaceWith('<div id="flash_tutor_msg" class="alert alert-info fade in"><%= escape_javascript(flash[:notice]).html_safe %></div>');
<% end %>

<% if flash[:error] %>
$('#myModalSignUp').modal('hide');
$(window).scrollTop($('#contact_form_box').offset().top);
$('#inner_contact_box').replaceWith('<div id="flash_tutor_msg" class="alert alert-error fade in"><%= escape_javascript(flash[:error]).html_safe %></div>');
<% end %>

<% flash[:notice], flash[:error] = nil, nil %>

app/views/tutors/search.js.erb
 var markers = <%=raw(@hash.to_json)%>
 
 initializeMap(markers);

 $('#search_result_container').html('<%= escape_javascript(render "map_view_list") %>');
 $('.pagination').html('<%=  escape_javascript(paginate(@user_details, :remote => true)) %>');
 $('#page_numbers').html('<%= escape_javascript(render "page_numbers") %>');


  

app/views/tutors/send_message_via_ajax.js.erb
<% if flash[:success] %>
    $("#user_messages_message").val("");

    //$('#success_box').replaceWith('<div id="flash_tutor_msg1" class="alert alert-info fade in"><%= escape_javascript(flash[:success]).html_safe %><button class="close" data-dismiss="alert" type="button">×</button></div>');
    //$("#tbldata tr:first").after("<tr>"+"<td><%= User.find(@user_message.student_id).first_name %></td>"+"<td><%= @user_message.message %></td>"+"<td><%= @user_message.created_at %></td>"+"</tr>");

    var pro_white_bg = $(".new_scroll_col ul:first").attr("class") != "pro_white_bg"? "pro_white_bg": "";

    var msgHtml =  "<ul class="+pro_white_bg+">"+
                      "<li><%= User.find(@user_message.student_id).first_name %></li>"+
                      "<li class='wdt70'><%= @user_message.message %></li>" +
                      "<li class='wdt18'><%= @user_message.created_at %></li>"+
                    "</ul>";

    $(".new_scroll_col").prepend(msgHtml);

    setTimeout(function(){
	    $("#success_box").css("display","none");
	},5000)

    <% flash[:success],flash[:error] = nil,nil %>
<% end %>

app/views/tutors/student_close_account.html.erb
<div class="wrapper">
  <div class="nice-box close-account" id="login">
    <div class="header">
      <h2><%= t('settings.close_heading') %></h2>
    </div>
    <div class="body">
      <%= t('settings.close_txt') %>
      <br><br>
      
      <form method="post" action="/tutors/<%= @user.id%>/student_confirm_close_account">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <input type="hidden" value="yes" name="confirm" id="confirm">
        <input type="submit" value="<%= t('settings.close_confirm') %>" name="commit">
        <%= t('settings.or') %>
        <a class="cancel" href="/tutors/student_setting/<%= @user.id%>"><%= t('settings.close_cancel') %></a>
      </form>
    </div>
  </div>
</div>