config/routes.rb
SouFudao::Application.routes.draw do

  resources :paypal_payments do
    collection do
      get '/featured_payment/:id' => "paypal_payments#featured_payment"
      get '/featured_payment_monthly' => "paypal_payments#featured_payment_monthly"
      get '/featured_payment_yearly' => "paypal_payments#featured_payment_yearly"
      get '/review/:id' => "paypal_payments#review"
      get '/cancel/:id' => "paypal_payments#cancel"      
      get '/cancel_recurring/:id' => "paypal_payments#cancel_recurring"            
      get '/make_recurring' => "paypal_payments#make_recurring"
      get '/notification/:payment_id' => "paypal_payments#notification"
    end
  end

  resources :user_details do
    collection do
      get 'update_password'
      get '/:id/profile_completion_step2' => 'user_details#profile_completion_step2'
      post '/:id/update_user_details' => 'user_details#update_user_details'
      put '/update_profile_visibility/:id' => 'user_details#update_profile_visibility'
      put '/email_updates_flag/:id' => 'user_details#email_updates_flag'

      patch '/save_user_avatar/:id' => "user_details#save_user_avatar"
      get '/remove_user_avatar/:id' => "user_details#remove_user_avatar"
      post '/:id/update_user_subjects' => 'user_details#update_user_subjects'
      post '/:id/update_user_info' => 'user_details#update_user_info'
      post '/:id/update_phone_info' => 'user_details#update_phone_info'

      get '/:id/profile_completion_step3' => 'user_details#profile_completion_step3'
      get '/save_listing_type/:id' => 'user_details#save_listing_type'
      get '/my_account/:id' => 'user_details#my_account'
      post '/:id/update_availability_info' => 'user_details#update_availability_info'
      post '/:id/update_location_details' => 'user_details#update_location_details'

      post '/save_user_avatar/:id' => "user_details#save_user_avatar"

      get 'add_time_select' => "user_details#add_time_select"
      get 'add_distance_select' => "user_details#add_distance_select"
      post '/invite_a_friend/:id' => "user_details#invite_a_friend"
      get 'add_more_degree' => "user_details#add_more_degree"
      get 'get_districts' => "user_details#get_districts"
    end
  end

  resources :tutors do
    collection do 
      get 'tutor/:id' => 'tutor#profile'
      get '/my_client/:id' => 'tutors#my_client'
      get '/settings/:id' => 'tutors#settings'
      get '/upgrade/:id' => 'tutors#upgrade'
      get '/my_messages/:id' => 'tutors#my_messages'      
      post '/:id/save_tutor_message' => 'tutors#save_tutor_message'
      get '/close_account/:id' => "tutors#close_account"
      post '/:id/confirm_close_account' => 'tutors#confirm_close_account'
      get '/student_close_account/:id' => "tutors#student_close_account"
      post '/:id/student_confirm_close_account' => 'tutors#student_confirm_close_account'
      get '/account_closed_message' => 'tutors#account_closed_message'

      post '/search' => 'tutors#search'
      get '/search' => 'tutors#search'
      post '/search_list_view' => 'tutors#search_list_view'
      get '/search_list_view' => 'tutors#search_list_view'

      get '/student/:id' => 'tutors#student'
      get '/student_setting/:id' => 'tutors#student_setting'
      get '/invite_students_friend/:id' => 'tutors#invite_students_friend' 
      post '/update_student_data/:id' => 'tutors#update_student_data'
      post '/tell_a_friend/:id' => 'tutors#tell_a_friend'
      post '/save_rate_reviews/tutor_id' => 'tutors#save_rate_reviews'
      get '/reload_capcha' => 'tutors#reload_capcha'
      post '/create_student_user' => "tutors#create_student_user"
      post '/student_sign_in' => "tutors#student_sign_in"
      get '/show_msg_conversation/:other_user_id' => "tutors#show_msg_conversation"
      post '/send_message_via_ajax' => "tutors#send_message_via_ajax"
      get '/student_messages/:id' => "tutors#student_messages" 
      get '/show_msg_conversation_for_student/:other_user_id' => "tutors#show_msg_conversation_for_student"
      get '/send_saved_message' => "tutors#send_saved_message"

    end
  end

  resources :subscriptions do
    collection do
      post '/request_to_yoopay' => "subscriptions#request_to_yoopay"
    end
  end

  get '/home' => 'home#index', as: 'home'
  get '/page_not_found' => 'home#page_not_found', as: 'page_not_found'
  get '/about' => 'home#about', as: 'about'
  get '/faq' => 'home#faq', as: 'faq'
  get '/contact' => 'home#contact', as: 'contact'
  get '/search_tutors' => "home#search_tutors"
  get '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  get '/notify_url' => 'subscriptions#notify_url'
  get '/return_url' => 'subscriptions#return_url'

  resources :home do
    collection do 
        post '/save_contact' => 'home#save_contact'
        get '/change_locale' => 'home#change_locale'
    end
  end

  devise_for :users
  

  root 'home#search_tutors'

end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode

  attr_accessible :user_id, :is_visible?, :is_profile_complete?, :gender, :street_add, :city, :country, :zip_code,
				  :state, :user_attributes, :avatar, :subject, :education, :experience, :hobbies, :is_plan_selected?, :invite_counter, :listing_type, :latitude, :longitude, :district, :age

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  #accepts_nested_attributes_for :user

serialize :education

def address
  [street_add, city, district, country].compact.join(' ')
end

def location
  [city, country].compact.join(', ')
end

def is_basic_info_complete?
	!(self.user.first_name.blank? || self.user.last_name.blank? || self.user.email.blank? || self.gender.blank?)
end  

def is_location_info_complete?
  # !(self.city.blank? || self.state.blank? || self.country.blank?)
  !(self.city.blank? || self.district.blank? || self.country.blank?)
end

def is_subject_info_complete?
	!(self.subject.blank?)
end 

def is_about_you_info_complete?
	!(self.experience.blank? || self.hobbies.blank?)
end 

def is_availability_info_complete?
	!(self.user.availability.price.blank? || self.user.availability.distance.blank? || self.user.availability.currency.blank? || self.user.availability.time.blank? )
end

#This method is for optional photo field
def is_photo_info_complete?
	!(self.avatar.blank?)
end

#This method is for optional phone field
def is_phone_chat_info_complete?
  contact_info = UserContactInfo.find_by_user_id(self.user_id)
	!(contact_info.phone.blank? && contact_info.qq_chat_id.blank? && contact_info.we_chat_id.blank? && contact_info.skype_id.blank?) unless contact_info.nil?
end

# To check 45sections of profile step 2 if completed by user or not
def is_user_profile_done?
	(is_basic_info_complete? && is_location_info_complete? && is_subject_info_complete? && is_about_you_info_complete? && is_availability_info_complete?)
end

def is_profile_and_listing_done?
	(is_user_profile_done? && self.is_plan_selected?)
end
 
def get_user_avatar
	!(self.avatar.blank?) ? self.avatar.url(:thumb) : "/assets/no_profile_pic.gif"	      				
end

# On Profile page if any one of the section out of 4 is incomplete then set is_visible to false.
def will_profile_visible?
	(self.is_visible? && is_user_profile_done?)
end

def show_listing_type
	(self.listing_type ? "Free Listing" : "Premium Listing" )
end

def average_rating
@tutor = self.user
  sum_rate = 0
  avg = 0 
  @tutor.tutor_review.each do |review_obj|
    sum_rate = sum_rate + review_obj.rate
  end
  avg = (sum_rate / @tutor.tutor_review.count).to_i if (@tutor.tutor_review.count != 0)
  avg
end

def get_count_of_new_msgs
  UserMessages.where('user_id = ? and created_at > ?',self.user.id, self.user.last_sign_in_at).count
end
end

app/controllers/user_details_controller.rb
#!/bin/env ruby
# encoding: utf-8
class UserDetailsController < ApplicationController
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:my_account,:profile_completion_step2,:profile_completion_step3]

  # GET /user_details
  # GET /user_details.json
  def index
    @user_details = UserDetail.all
  end

  # GET /user_details/1
  # GET /user_details/1.json
  def show
  end

  # GET /user_details/new
  def new
    @user_detail = UserDetail.new
  end

  # GET /user_details/1/edit
  def edit
  end

  # POST /user_details
  # POST /user_details.json
  def create
    @user_detail = UserDetail.new(user_detail_params)

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to @user_detail, flash[:notice] = (session[:locale] != "cn") ? 'User details successfully created.' : '保存成功' }
        format.json { render action: 'show', status: :created, location: @user_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

def save_user_avatar
    @user_detail = set_user_detail
    @user_avatar = params[:user_detail][:avatar] if params[:user_detail][:avatar]
    if @user_detail.update(:avatar => @user_avatar)
      flash[:notice] = (session[:locale] != "cn") ? "Photo updated successfully" : '保存成功'
    else
      flash[:notice] = (session[:locale] != "cn") ? "Error uploading photo. Please try again." : "出错了，请再试一次。"
    end 
    redirect_to :back
end

def remove_user_avatar
      @user_detail = set_user_detail
      @user_detail.avatar = nil
      @user_detail.save
      flash[:notice] = (session[:locale] != "cn") ? "Photo has been removed" : "照片已删除"
      redirect_to :back
end

def update_user_subjects
  @user_detail = set_user_detail
  if @user_detail.update(:subject => params[:user_details][:subject])
    flash[:notice] = (session[:locale] != "cn") ? "Subjects saved successfully" : "保存成功"
  else  
    flash[:error] = (session[:locale] != "cn") ? "Sorry, Subjects could not be saved. Please try again." : "出错了，请再试一次。"
  end
  @subject_status, @profile_status = @user_detail.is_subject_info_complete?, @user_detail.is_user_profile_done?
  respond_to do |format|
    format.js 
  end
end

def update_user_info
  @user_detail = set_user_detail
  @user_lang_params = params[:user_language].merge("user_id"=> @user_detail.user_id)
  if @user_detail.update(:education => params[:user_details][:education], :experience => params[:user_details][:experience], :hobbies => params[:user_details][:hobbies])
      if @user_detail.user.user_language.blank? 
        @user_lang = UserLanguage.new(@user_lang_params) unless params[:user_language].blank?
        @user_lang.save
      else
        @user_lang = @user_detail.user.user_language
        @user_lang.update(:english_rate => @user_lang_params[:english_rate], :chinese_rate => @user_lang_params[:chinese_rate], :lang_spoken => @user_lang_params[:lang_spoken])
      end
      flash[:notice] = (session[:locale] != "cn") ? "About You saved successfully" : "保存成功"
  else
      flash[:error] = (session[:locale] != "cn") ? "Sorry, About You information could not be saved. Please try again." : "出错了，请再试一次。"
  end 
    @about_you_status, @profile_status = @user_detail.is_about_you_info_complete?, @user_detail.is_user_profile_done?
    respond_to do |format|
    format.js 
  end
end

def update_phone_info
    @user_detail = set_user_detail
    @info = params[:user_contact_info]
    @contact_info = UserContactInfo.find_by_user_id(@user_detail.user_id)
    if @contact_info 
      @contact_info.update(:phone => @info[:phone], :qq_chat_id => @info[:qq_chat_id], :we_chat_id => @info[:we_chat_id], :skype_id => @info[:skype_id])
    else
      @contact_info = UserContactInfo.new(@info)
      @contact_info.save
    end  
    flash[:notice] = (session[:locale] != "cn") ? "Contact Information saved successfully" : "保存成功"
    @phone_status, @profile_status = @user_detail.is_phone_chat_info_complete?, @user_detail.is_user_profile_done?
    respond_to do |format|
    format.js 
  end
end

def profile_completion_step3
  @user_detail = UserDetail.find_by_user_id(current_user.id)
  @user_detail.update(:is_profile_complete? => true)
end

  # PATCH/PUT /user_details/1
  # PATCH/PUT /user_details/1.json
  def update
    respond_to do |format|
      if @user_detail.update(user_detail_params)
        format.html { redirect_to @user_detail, notice: 'Details successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.json
  def destroy
    @user_detail.destroy
    respond_to do |format|
      format.html { redirect_to user_details_url }
      format.json { head :no_content }
    end
  end

  def update_password
    unless current_user.nil?
      @user = current_user
      @current_user_detail = UserDetail.find_by_user_id(@user.id)
    else
      flash[:notice] = (session[:locale] != "cn") ? "Sorry, you are not logged in. Please log in and try again." : "请先登陆。"
    end
  end

  def profile_completion_step2
      city_states = YAML.load_file('config/city_states.yml')
      @cities = city_states['china'].keys
      @districts = city_states['china']['Shanghai']

    @user_detail = UserDetail.find(params[:id])
    @user = User.find(@user_detail.user_id)
    @availability = @user.availability
    @available_day = Availability::TIME_DAY
    @available_time = Availability::TIME_TIME
    @availability_location = Availability::DISTANCE_LOCATION
    @availability_rate = Availability::DISTANCE_RATE    
  end

  def update_user_details
      @user_detail = UserDetail.find(params[:id])
      @user = @user_detail.user
      details = params[:user_details]
      dob = params[:user_details]["age(3i)"]+"-"+params[:user_details]["age(2i)"]+"-"+params[:user_details]["age(1i)"] unless (params[:user_details]["age(3i)"].blank? ||  params[:user_details]["age(2i)"].blank? || params[:user_details]["age(1i)"].blank?)
      @user_lang_params = params[:user_language].merge("user_id" => @user_detail.user_id) unless params[:user_language].blank?      
          #if @user_detail.update(:street_add => details[:street_add], :city => details[:city], :state => details[:state], 
          #                   :country => details[:country], :zip_code => details[:zip_code], :gender => details[:gender]) && @user.update(:first_name => details[:first_name], :last_name => details[:last_name], :email => details[:email])
          if (@user_detail.update(:gender => details[:gender]) && @user.update(:first_name => details[:first_name], :last_name => details[:last_name], :email => details[:email]))
               @user_detail.update(:age => dob.to_date) unless dob.blank?            
            if @user.user_language.blank? 
              @user_lang = UserLanguage.new(@user_lang_params) unless params[:user_language].blank?
              @user_lang.save
            else
              @user_lang = @user.user_language
              @user_lang.update(:nationality => @user_lang_params[:nationality])
            end 
            flash[:notice] = (session[:locale] != "cn") ? 'Basic Info saved successfully.' : "保存成功"
          else
            flash[:error] = true
          end
      @basic_info_status, @profile_status = @user_detail.is_basic_info_complete?, @user_detail.is_user_profile_done?
      respond_to do |format|
        format.js 
      end
  end

  def update_location_details
    @user_detail = UserDetail.find(params[:id])
    details = params[:user_details]
    if @user_detail.update(:street_add => details[:street_add], :city => details[:city], :state => details[:state], 
                             :country => details[:country], :zip_code => details[:zip_code], :district => details[:district]) 
      flash[:notice] = (session[:locale] != "cn") ? 'Location updated successfully.' : "保存成功"
    else
        flash[:error] = (session[:locale] != "cn") ? 'Sorry, Location could not be saved. Please try again.' : "粗错了，请再试一次。"
    end
    @hash = Gmaps4rails.build_markers([@user_detail]) do |t, marker|
      marker.lat t.latitude
      marker.lng t.longitude
      # marker.infowindow user_detail.experience
        marker.picture({
       "url" => "/assets/blue-dot1.png",
        "width" =>  32,
        "height" => 32})
    end
      @location_info_status, @profile_status = @user_detail.is_location_info_complete?, @user_detail.is_user_profile_done?
      respond_to do |format|
        format.js 
      end    
  end

  def update_profile_visibility
      @user_detail = UserDetail.find(params[:id])
      if params[:is_visible] && @user_detail.is_user_profile_done? 
        @user_detail.update(:is_visible? => params[:is_visible]) unless params[:is_visible].nil?
      else
        @user_detail.update(:is_visible? => false) 
        flash[:notice] = (session[:locale] != "cn") ? "Please complete your profile before setting it to public. " : "请先完成资料填写。"
      end
      redirect_to :back
  end


  def save_listing_type
    @user_detail = UserDetail.find_by_user_id(current_user.id)
    if @user_detail.update(:is_plan_selected? => true)
      redirect_to :controller => "tutors",:action => "show", :id=>@user_detail.user_id
    else
      flash[:notice] = (session[:locale] != "cn") ? "Sorry, please try again" : "请再试一次"
      redirect_to :back
    end    
  end

  def update_availability_info
      availability = Availability.find_by_user_id(current_user.id)
      availability.user_id = current_user.id
      availability.time = nil unless params[:user][:time]
      availability.distance = nil unless params[:user][:distance]

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_cities.html.erb
<% if params[:city] 
    city_param = params[:city] 
else
	city_param = @user_detail ? @user_detail.city : ' '
end %>
<% @cities.each do |city| %>
	<option value="<%= city %>" <%= "selected" if city_param == city %>  ><%= t("cities.#{city}") %></option>
<% end %>

app/views/user_details/_form.html.erb
<%= form_for(@user_detail) do |f| %>
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>
      <ul>
        <% @user_detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user do |field| %>
    <%= field.label "First Name" %>
    <%= field.text_field :first_name %>
    <%= field.label "Last Name" %>
    <%= field.text_field :last_name %>
    <%= field.label "Email" %>
    <%= field.text_field :email %>
    <%= field.label "Password" %>
    <%= link_to "Change your password", edit_user_registration_path %>
  <% end %>

  <div class="field">
    <%= f.label "Street Address" %>
    <%= f.text_field :street_add %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label "State/Region" %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.radio_button :gender, "Male" %><%= f.label "Male" %>
    <%= f.radio_button :gender, "Female" %><%= f.label "Female" %>
  </div>
  <div class="actions">
    <input type="submit" value="Save Changes" name="commit"/>
  </div>
<% end %>

app/views/user_details/_subjects_form.html.erb
<%= form_for(:user_details, :url => {:action=>:update_user_subjects}, :html => {:id=> "subject_form",:method => :post, :remote => true}) do |f| %>


  <div class="account_col chose_sub_col">

      <div class="account_fild_col">
       
        

        <div class="account_lft_col">
          <p> <%= t('subjects.select_sub') %> :</p>
          <%= render :partial => 'choose_subjects' %>
          <span id="suggest_subjects_error" class="err_msg"></span>
        </div>
	
	<div class="account_rht_col">
	  <ul id='subjects_list' class='list-panel subject-list'>
	    <%if @user_detail.subject.present?%>
	      <%- @user_detail.subject.split(',').each do |item| -%>
	        <%unless item.strip.blank? %>
		  <li>
		    <%= t("subjects.#{item.strip}") %>
		    <a href="javascript:void(0)" onclick="removeItem(this)" data-text='<%=t("subjects.#{item.strip}")%>'  data-remove-text='<%=item.strip %>'>X</a>
		  </li>
		<%end%>
	      <%end %>
	    <%end%>  
	  </ul>
          <%= f.text_area :subject, :value => @user_detail.subject ?  @user_detail.subject : nil,  :style => "  word-wrap: break-word; resize: none; overflow:hidden;display:none;" %>
        </div>
      </div>
  </div>


	<div class="profilesubmit fl_none">
    	<input type="submit" value="<%= t('save_changes_btn_txt') %>" id="post_basic_info" name="commit"/>
  	</div>
<% end %>
<script type="text/javascript">
function set_subjects(sel){
	var d = sel.options[sel.selectedIndex].text; 
	var text_data = $("#user_details_subject").val();
	if(text_data.indexOf(d) == -1)
	{
	  if($("#user_details_subject").val() == ""){
	    $("#user_details_subject").val(d);
	    $("#subjects_list").append('<li>'+d+'<a href="javascript:void(0)" onclick="removeItem(this)" data-text="'+ d+' data-remove-text='+d+'">X</a></li>');
	  }else{
	    var updated_data = text_data + ", " + d;
	    $("#user_details_subject").val(updated_data).trigger('autosize.resize');
	    $("#subjects_list").append('<li>'+d+'<a href="javascript:void(0)" onclick="removeItem(this)" data-text="'+ d+' data-remove-text='+d+'">X</a></li>');
	  }  
	}
	
}

$(document).ready(function(){
  $('#user_details_subject').autosize();

 // add the rule here
 $.validator.addMethod("valueNotEquals", function(value, element, arg){
  return arg != value;
 }, "Value must not equal arg.");

  $("#subject_form").validate({
  rules: {
   "suggest_subjects": { valueNotEquals: "any-subject" }
  },
  messages: {
   "suggest_subjects": { valueNotEquals: "<%= t('signup.enter_value')%>" }
  },  

      showErrors: function (errorMap, errorList) {

        $.each(this.successList, function (index, value) {
          //console.log(value.id)
          $("#"+value.id+"_error").html(" ");
          $("#"+value.id).css("border","1px solid #CCCCCC");
        });


        $.each(errorList, function (index, value) {
          //console.log(value.element.id);
          //console.log(value.message);
            $("#"+value.element.id+"_error").html(value.message);
            $("#"+value.element.id).css("border","1px solid red");                      
        });

      }      

 });
});

function removeItem(item)
{
  
  remove_text = $(item).attr('data-remove-text');
  if($('#user_details_subject').val().indexOf(remove_text+',') != -1)
  {
    remove_text= remove_text+','
  }
  
  $(item).parent().remove()
  $("#user_details_subject").val( $('#user_details_subject').val().replace(remove_text ,'') )
}
</script>

app/views/user_details/_time_select.html.erb
  <div class="available_time">

  <select name="user[time][][day]" id="user_available_time_attributes__day">
      <% @available_day.each do |key, val| %>
        <option value="<%= key%>"><%= t "days.#{val}" %>
        </option>
      <% end %>  
  </select>
       
  <select name="user[time][][time]" id="user_available_time_attributes__time">
      <% @available_time.each do |key, val| %>
        <option value="<%= key%>"><%= t "times.#{val}" %>
        </option>
      <% end %>  
  </select>
   <a href="javascript:void(0);" onclick="$(this).parent().remove();"><%= t('remove') %></a>
  </div>

app/views/user_details/add_more_degree.js.erb
$('#degrees_portion_partial').append("<%= escape_javascript(render :partial => 'add_more_degree').html_safe %>")

app/views/user_details/get_districts.js.erb
	$('#district_select').html("<%= escape_javascript(render :partial => 'districts', :districts => @districts).html_safe %>")	

app/views/user_details/index.html.erb
<h1>Listing user_details</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Is profile complete?</th>
      <th>Is visible?</th>
      <th>Street add</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zip code</th>
      <th>Gender</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_details.each do |user_detail| %>
      <tr>
        <td><%= user_detail.user_id %></td>
        <td><%= user_detail.is_profile_complete? %></td>
        <td><%= user_detail.is_visible? %></td>
        <td><%= user_detail.street_add %></td>
        <td><%= user_detail.city %></td>
        <td><%= user_detail.state %></td>
        <td><%= user_detail.country %></td>
        <td><%= user_detail.zip_code %></td>
        <td><%= user_detail.gender %></td>
        <td><%= link_to 'Show', user_detail %></td>
        <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
        <td><%= link_to 'Destroy', user_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User detail', new_user_detail_path %>

app/views/user_details/update_availability_info.js.erb
$('#flash_msg_availability').css("display","block");
<% if flash[:notice] %>
$('#flash_msg_availability').html("<%= escape_javascript(flash[:notice]).html_safe %>");
<% elsif flash[:error] %>
$('#flash_msg_availability').html("<%= escape_javascript(flash[:error]).html_safe %>");
<% end %>
$(window).scrollTop($('#availability_div').offset().top);
<% flash[:notice], flash[:error] = nil, nil %>
setTimeout(function(){$('#flash_msg_availability').css("display","none");
},3000);


<% status = @availability_status ? "#{t('complete')} #{image_tag('/assets/check-mark.gif')}".html_safe : "#{t('incomplete')}" %>
$('#availability_info_status').html('<%= status %>');
<% if @profile_status %>
$('#continue_btn').show();
$('#continue_btn_alert').hide();
<% else %>
$('#continue_btn').hide();
$('#continue_btn_alert').show();
<% end %>
$("#my_profile_1").load();

app/views/user_details/update_user_details.js.erb
$('#flash_basic_msg').css("display","block");
$('#flash_basic_msg').html("");
<% if flash[:notice] %>
$('#flash_basic_msg').html("<%= escape_javascript(flash[:notice]).html_safe %>");
<% elsif flash[:error] %>
<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |msg| %>
			$('#flash_basic_msg').append("<%= escape_javascript(msg).html_safe %><br/>");
        <% end %>
<% end %>

<% if @user_detail.errors.any? %>
	<% @user_detail.errors.full_messages.each do|msg|%>
			$('#flash_basic_msg').html("<%= escape_javascript(msg).html_safe %><br/>");
    <% end %>
<% end %>

<% else %>
$('#flash_basic_msg').css("display","none");
<% end %>
$(window).scrollTop($('#basic_info_div').offset().top);
<% flash[:notice],flash[:error] = nil, nil %>
setTimeout(function(){$('#flash_basic_msg').css("display","none");
},3000);
<% status = @basic_info_status ? "#{t('complete')} #{image_tag('/assets/check-mark.gif')}".html_safe : "#{t('incomplete')}" %>
$('#basic_info_status').html('<%= status %>');
<% if @profile_status %>
$('#continue_btn').show();
$('#continue_btn_alert').hide();
<% else %>
$('#continue_btn').hide();
$('#continue_btn_alert').show();
<% end %>
$("#my_profile_0").load();