config/routes.rb
SouFudao::Application.routes.draw do

  resources :paypal_payments do
    collection do
      get '/featured_payment/:id' => "paypal_payments#featured_payment"
      get '/featured_payment_monthly' => "paypal_payments#featured_payment_monthly"
      get '/featured_payment_yearly' => "paypal_payments#featured_payment_yearly"
      get '/review/:id' => "paypal_payments#review"
      get '/cancel/:id' => "paypal_payments#cancel"      
      get '/cancel_recurring/:id' => "paypal_payments#cancel_recurring"            
      get '/make_recurring' => "paypal_payments#make_recurring"
      get '/notification/:payment_id' => "paypal_payments#notification"
    end
  end

  resources :user_details do
    collection do
      get 'update_password'
      get '/:id/profile_completion_step2' => 'user_details#profile_completion_step2'
      post '/:id/update_user_details' => 'user_details#update_user_details'
      put '/update_profile_visibility/:id' => 'user_details#update_profile_visibility'
      put '/email_updates_flag/:id' => 'user_details#email_updates_flag'

      patch '/save_user_avatar/:id' => "user_details#save_user_avatar"
      get '/remove_user_avatar/:id' => "user_details#remove_user_avatar"
      post '/:id/update_user_subjects' => 'user_details#update_user_subjects'
      post '/:id/update_user_info' => 'user_details#update_user_info'
      post '/:id/update_phone_info' => 'user_details#update_phone_info'

      get '/:id/profile_completion_step3' => 'user_details#profile_completion_step3'
      get '/save_listing_type/:id' => 'user_details#save_listing_type'
      get '/my_account/:id' => 'user_details#my_account'
      post '/:id/update_availability_info' => 'user_details#update_availability_info'
      post '/:id/update_location_details' => 'user_details#update_location_details'

      post '/save_user_avatar/:id' => "user_details#save_user_avatar"

      get 'add_time_select' => "user_details#add_time_select"
      get 'add_distance_select' => "user_details#add_distance_select"
      post '/invite_a_friend/:id' => "user_details#invite_a_friend"
      get 'add_more_degree' => "user_details#add_more_degree"
      get 'get_districts' => "user_details#get_districts"
    end
  end

  resources :tutors do
    collection do 
      get 'tutor/:id' => 'tutor#profile'
      get '/my_client/:id' => 'tutors#my_client'
      get '/settings/:id' => 'tutors#settings'
      get '/upgrade/:id' => 'tutors#upgrade'
      get '/my_messages/:id' => 'tutors#my_messages'      
      post '/:id/save_tutor_message' => 'tutors#save_tutor_message'
      get '/close_account/:id' => "tutors#close_account"
      post '/:id/confirm_close_account' => 'tutors#confirm_close_account'
      get '/student_close_account/:id' => "tutors#student_close_account"
      post '/:id/student_confirm_close_account' => 'tutors#student_confirm_close_account'
      get '/account_closed_message' => 'tutors#account_closed_message'

      post '/search' => 'tutors#search'
      get '/search' => 'tutors#search'
      post '/search_list_view' => 'tutors#search_list_view'
      get '/search_list_view' => 'tutors#search_list_view'

      get '/student/:id' => 'tutors#student'
      get '/student_setting/:id' => 'tutors#student_setting'
      get '/invite_students_friend/:id' => 'tutors#invite_students_friend' 
      post '/update_student_data/:id' => 'tutors#update_student_data'
      post '/tell_a_friend/:id' => 'tutors#tell_a_friend'
      post '/save_rate_reviews/tutor_id' => 'tutors#save_rate_reviews'
      get '/reload_capcha' => 'tutors#reload_capcha'
      post '/create_student_user' => "tutors#create_student_user"
      post '/student_sign_in' => "tutors#student_sign_in"
      get '/show_msg_conversation/:other_user_id' => "tutors#show_msg_conversation"
      post '/send_message_via_ajax' => "tutors#send_message_via_ajax"
      get '/student_messages/:id' => "tutors#student_messages" 
      get '/show_msg_conversation_for_student/:other_user_id' => "tutors#show_msg_conversation_for_student"
      get '/send_saved_message' => "tutors#send_saved_message"

    end
  end

  resources :subscriptions do
    collection do
      post '/request_to_yoopay' => "subscriptions#request_to_yoopay"
    end
  end

  get '/home' => 'home#index', as: 'home'
  get '/page_not_found' => 'home#page_not_found', as: 'page_not_found'
  get '/about' => 'home#about', as: 'about'
  get '/faq' => 'home#faq', as: 'faq'
  get '/contact' => 'home#contact', as: 'contact'
  get '/search_tutors' => "home#search_tutors"
  get '/simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  get '/notify_url' => 'subscriptions#notify_url'
  get '/return_url' => 'subscriptions#return_url'

  resources :home do
    collection do 
        post '/save_contact' => 'home#save_contact'
        get '/change_locale' => 'home#change_locale'
    end
  end

  devise_for :users
  

  root 'home#search_tutors'

end

app/views/layouts/_footer.html bkup.erb
<% title = content_for?(:title) ? yield(:title) : "SouFudao" %>
<% data_to_share_to_twitter = "#{title} #{request.original_url} Check it out!"%>
<table class="pull-right">
  <tbody>
    <tr> 
      <td>
        <%= t 'footer.Chinese Social Media' %>:
      </td>   
      <td style="vertical-align:top;width:20px;">
       
      </td>
      <td >
        
      </td>
      <td>
       
      </td>
      <td>
        
      </td>
    </tr>
    <tr>
      <td>
        <%= t 'footer.International Social Media' %>:
      </td> 
      <td style="vertical-align:top;width:20px;">
        <div class="fb-like" data-href="<%= request.original_url%>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
      </td>
      <td >
        <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-count="horizontal" data-text="<%= data_to_share_to_twitter %>"><%= image_tag("/assets/twitter.png")%></a>
      </td>
      <td>
        <script type="IN/Share" data-url="<%= request.original_url%>" data-counter="right"></script>
      </td>
      <td>
        <div class="g-plusone" data-size="medium" data-href="<%= request.original_url%>"></div>
      </td>
    </tr>
  </tbody>
</table>


<div class="modal hide" id="terms_model_footer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel1" style="text-align:center"><b>Sou Fudao Terms of Use</b></h3>
      </div>
      <div class="modal-body" style="font-weight:normal;">
      <%= render :partial => "/home/terms_of_use"%>  
      </div>
    </div>
  </div>
</div>

<div class="modal hide" id="privacy_model_footer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel2" style="text-align:center"><b>Sou Fudao Privacy Policy</b></h3>
      </div>
      <div class="modal-body" style="font-weight:normal;">
      <%= render :partial => "/home/privacy_policy"%>  
      </div>
    </div>
  </div>
</div>

<!-- Place this tag after the last +1 button tag. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
  $(window).bind("load", function() {
    $('.twitter-share-button').css("width","76px")
  });
</script>

app/views/layouts/_footer.html.erb
<% title = content_for?(:title) ? yield(:title) : "SouFudao" %>
<% data_to_share_to_twitter = "#{title} #{request.original_url} Check it out!"%>

<div class="fotter_rht">
  <div class="social_icon">
    <!--<h6> <%#= t 'footer.Chinese Social Media' %>:</h6>
      <img src="/assets/wechat_icon.png"  />
     <img src="/assets/qq_icon.png"  />
     <img src="/assets/sina_icon.png"  />
     <img src="/assets/renren_icon.png"  />
  </div>-->
   <!--<div class="social_icon">
    <h6> <%#= t 'footer.International Social Media' %>:</h6>
    <a href="https://www.facebook.com/soufudao" target="_blank"> <img src="/assets/fb_icon.png"  />   </a>
    <a href="https://twitter.com/Soufudao" target="_blank">  <img src="/assets/twiter_icon.png"  />   </a>
    <a href="https://plus.google.com/115859555925092649781/posts" target="_blank"> <img src="/assets/google_icon.png"  />   </a>-->
     <!--<img src="/assets/linked_icon.png"  />-->
    <a href="javascript:void(0);" onclick="$('#wechat_model_footer').modal();"> <img src="/assets/wechat_icon.png"  width="37"/>   </a>
    <a href="http://weibo.com/u/5135883018" target="_blank"> <img src="/assets/sina_icon.png"  />   </a>
    <a href="http://t.qq.com/soufudaojiajiao" target="_blank"> <img src="/assets/weibo_icon.png"  />   </a>
    <a href="https://www.facebook.com/soufudao" target="_blank"> <img src="/assets/fb_icon.png"  />   </a>
    <a href="https://twitter.com/Soufudao" target="_blank">  <img src="/assets/twiter_icon.png"  />   </a>
    <a href="https://plus.google.com/115859555925092649781/posts" target="_blank"> <img src="/assets/google_icon.png"  />   </a>
	
  </div>
	
</div>


<div class="modal hide" id="wechat_model_footer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel1" style="text-align:center">
	  <b><%= t 'footer.wechat_account' %>:
	    <span style='color:#84CCF5'> SouFudao </span>
	  </b>
	</h3>
      </div>
      <div class="modal-body wechat-panel" >
	<img src='/assets/WeChat_QR_code.jpg' class='QR-image'>
      </div>
    </div>
  </div>
</div>


<div class="modal hide" id="terms_model_footer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel1" style="text-align:center"><b>Sou Fudao Terms of Use</b></h3>
      </div>
      <div class="modal-body" style="font-weight:normal;">
      <%= render :partial => "/home/terms_of_use"%>  
      </div>
    </div>
  </div>
</div>

<div class="modal hide" id="privacy_model_footer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title" id="myModalLabel2" style="text-align:center"><b>Sou Fudao Privacy Policy</b></h3>
      </div>
      <div class="modal-body" style="font-weight:normal;">
      <%= render :partial => "/home/privacy_policy"%>  
      </div>
    </div>
  </div>
</div>

<!-- Place this tag after the last +1 button tag. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
  $(window).bind("load", function() {
    $('.twitter-share-button').css("width","76px")
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/x-icon" href="../assets/BeeFavicon.ico">
  <!-- google maps -->
  <!-- // <script src="http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry,places" type="text/javascript"></script> -->
  <!-- // <script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> -->
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=1.4&amp;ak=VXA9UYtvEo8gS6fgCGNNPw0y"></script>
  <script type="text/javascript" src="http://api.map.baidu.com/library/SearchControl/1.4/src/SearchControl_min.js"></script>
  <link rel="stylesheet" href="http://api.map.baidu.com/library/SearchControl/1.4/src/SearchControl_min.css" />

  <!-- maps -->
  <title><%= content_for?(:title) ? yield(:title) : t('title_txt') %></title>
  <meta property="og:url" content="<%= request.url %>"/>
  <meta property="og:title" content="<%= "#{@tutor.subjects.first} Tutor #{@tutor.user_detail.city}, #{@tutor.user_detail.country}" if @tutor %>"/>
  <meta property="og:type" content="article"/>
  <meta property="og:description" content="<%= @tutor.user_detail.experience if @tutor %>"/>
  <meta name="medium" content="image"/>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <% if I18n.locale == :cn %><%= stylesheet_link_tag "locales/" + I18n.locale.to_s %>
  <% end %>

  <%= javascript_include_tag "application" %>


  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'BeeFavicon.ico', :rel => 'shortcut icon' %>
  <script type="text/javascript">var switchTo5x = true;</script>
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script src="http://nunavuttabletennis.com/newsite/js/jquery.bxslider.js"></script>
  <script type="text/javascript">
      stLight.options({
          publisher: "87b061cf-63ff-4419-a549-c60ff18101ac",
          doNotHash: true,
          doNotCopy: true,
          hashAddressBar: false,
          shorten:false,
          servicePopup: true
      });
  </script>
  <script>
      $(function() {
          var pull = $('#pull');
          menu = $('nav ul');
          menuHeight = menu.height();

          $(pull).on('click', function(e) {
              e.preventDefault();
              menu.slideToggle();
          });

          $(window).resize(function() {
              var w = $(window).width();
              if (w > 320 && menu.is(':hidden')) {
                  menu.removeAttr('style');
              }
          });

          $('.prod_main_slider1').bxSlider({
              infiniteLoop: false,
              autoDirection: 'next',
              nextText: 'next',
              prevText: 'prev',


          });

      });
  </script>


</head>
<body>
<div id="fb-root"></div>

<div id="header">


  <div class="wrapper " data-no-turbolink>
    <div id="head-left">
      <a href="/">
        <img src="/assets/soufudao2.png"/>
        <!--h2 style="float:left;margin-left:5px;color:#00457F;"> 搜辅导</h2>
       <p>Sou Fudao</p-->
      </a>
    </div>

    <div class="header_rht">

      <div class="span pull-right">
        <div class="blue_top_tab">
          <%= link_to '中文', :controller => '/home', :action => 'change_locale', :locale => 'cn' %>
          <%= link_to 'English', :controller => '/home', :action => 'change_locale', :locale => 'en' %>
        </div>
      </div>

      <nav class="clearfix">
        <a href="#" id="pull">Menu</a>
        <ul class="clearfix">
          <li><a href="/" class="<%= active_link('search_tutors') %>"><%= t('home') %></a></li>
          <li><a href="/about" rel="nofollow" class="<%= active_link('about') %>"><%= t('about') %></a></li>
          <li><a href="/contact" rel="nofollow" class="<%= active_link('contact') %>"><%= t('contact_us') %></a></li>
          <% if (user_signed_in? && current_user.is_tutor?) %>
              <% @user_details = UserDetail.find_by_user_id(current_user.id) %>
              <% my_account_url = redirect_after_sign_in(current_user) %>
              <li>
                <a href="<%= my_account_url %>" class="<%= active_link('my_account') %>" rel="login"><%= t('my_account_link') %></a>
              </li>
              <li><%= link_to "#{t('logout')}", destroy_user_session_path, :method => :delete, :tabindex=>"-1", :class=>"menu-item" %></li>
          <% elsif (user_signed_in? && !current_user.is_tutor?) %>
              <li>
                <a href="/tutors/student/<%= current_user.id %>" class="<%= active_link('my_account') %>" rel="login"><%= t('my_account_link') %></a>
              </li>
              <li><%= link_to "#{t('logout')}", destroy_user_session_path, :method => :delete, :tabindex=>"-1", :class=>"menu-item" %></li>
          <% else %>
              <li><a href="/users/sign_up" class="<%= active_link('sign_up') %>"><%= t('tutoring_jobs') %></a></li>
              <li><a href="/users/sign_in" class="<%= active_link('sign_in') %>" rel="login"><%= t('login') %></a></li>
          <% end -%>
        </ul>
      </nav>
    </div>
  </div>
</div>
<% flash_str = "<div class=\"alert fade in alert-error\"><button class=\"close\" data-dismiss=\"alert\">&times;</button>您的确认是无效的。</div>" %>
<%= bootstrap_flash.include?("Confirmation token是无效的") ? flash_str.html_safe : bootstrap_flash %>

<% if (params[:controller] == 'user_details' && params[:action] == "my_account") || (params[:controller] == 'user_details' && params[:action] == "profile_completion_step2") || (params[:controller] == 'user_details' && params[:action] == "profile_completion_step3") ||(params[:controller] == 'tutors' && (params[:action] == "show" || params[:action] == "my_messages" || params[:action] == "upgrade" || params[:action] == "settings" || params[:action] == "search" || params[:action] == "search_list_view" || params[:action] == "invite_students_friend" || params[:action] == "student_setting" || params[:action] == "student" || params[:action] == "student_messages"))
       ext_class = "no_chalkboard"
   end %>

 <% if (params[:controller] == "home" && params[:action] == "search_tutors")
         ext_class = "home"
   end
%>

<div class="middle_container <%= ext_class %>">
  <%= yield %>
</div>

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--%= javascript_include_tag "application" %-->
<div id="footer">
  <div class="wrapper">
    <div class="fotter_lft">&copy;2014 搜辅导 Sou Fudao
      <a href="javascript:void(0);" onclick="$('#privacy_model_footer').modal();"><%= t('privacy_policy') %></a>
      <a href="javascript:void(0);" onclick="$('#terms_model_footer').modal();"><%= t('terms_of_use') %></a>
    </div>
    <%= render :partial=>"layouts/footer" %>
  </div>
</div>

    <script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F3579b40a4a71e756957c9a74857c7250' type='text/javascript'%3E%3C/script%3E"));
    </script>

</body>
</html>
<script src="//platform.linkedin.com/in.js" type="text/javascript">
    lang: en_US
</script>

<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= get_fb_app_id["app_id"] %>";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>!function(d, s, id) {
    var js,fjs = d.getElementsByTagName(s)[0];
    if (!d.getElementById(id)) {
        js = d.createElement(s);
        js.id = id;
        js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);
    }
}(document, "script", "twitter-wjs");</script>

<script src="https://apis.google.com/js/plusone.js"></script>

<script src="//platform.linkedin.com/in.js" type="text/javascript">
    lang: en_US
</script>